
version: '2'

services:
  web:
    restart: 'always'
    build: ./web
    expose:
      - "8000"
    env_file:
        - .env
    volumes:
      - /usr/src/app/web/project/static
    command: /usr/local/bin/gunicorn -w 2 -b :8000 project:app
    depends_on:
      - postgres

  nginx:
    restart: 'always'
    build: ./nginx
    ports:
      - "80:80"
    volumes_from:
      - web
    depends_on:
      - web

  data:
    restart: 'no'
    image: postgres:11
    volumes:
      - /var/lib/postgresql
    command: "true"

  postgres:
    restart: 'always'
    image: postgres:11
    env_file:
      - .env
    volumes_from:
      - data
    ports:
      - "5432:5432"
